/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author felipe.guerrera
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_cadastrarprod = new javax.swing.JButton();
        bt_verprod = new javax.swing.JButton();
        bt_novoserv = new javax.swing.JButton();
        vt_verservico = new javax.swing.JButton();
        bt_cadastrarcliente = new javax.swing.JButton();
        bt_cadastrarpet = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        bt_cadastrarcargo = new javax.swing.JButton();
        bt_agendamento = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Menu Funcionários");

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Pet Shop Bicho Sacana");

        bt_cadastrarprod.setBackground(new java.awt.Color(0, 0, 255));
        bt_cadastrarprod.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        bt_cadastrarprod.setForeground(new java.awt.Color(255, 255, 0));
        bt_cadastrarprod.setText("Cadastrar Produtos");
        bt_cadastrarprod.setBorder(null);
        bt_cadastrarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarprodActionPerformed(evt);
            }
        });

        bt_verprod.setBackground(new java.awt.Color(0, 0, 255));
        bt_verprod.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        bt_verprod.setForeground(new java.awt.Color(255, 255, 0));
        bt_verprod.setText("Ver Produtos");
        bt_verprod.setBorder(null);
        bt_verprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verprodActionPerformed(evt);
            }
        });

        bt_novoserv.setBackground(new java.awt.Color(0, 0, 255));
        bt_novoserv.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        bt_novoserv.setForeground(new java.awt.Color(255, 255, 0));
        bt_novoserv.setText("Novo Serviço");
        bt_novoserv.setBorder(null);
        bt_novoserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoservActionPerformed(evt);
            }
        });

        vt_verservico.setBackground(new java.awt.Color(0, 0, 255));
        vt_verservico.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        vt_verservico.setForeground(new java.awt.Color(255, 255, 0));
        vt_verservico.setText("Ver Serviços");
        vt_verservico.setBorder(null);
        vt_verservico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vt_verservicoActionPerformed(evt);
            }
        });

        bt_cadastrarcliente.setBackground(new java.awt.Color(0, 0, 255));
        bt_cadastrarcliente.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        bt_cadastrarcliente.setForeground(new java.awt.Color(255, 255, 0));
        bt_cadastrarcliente.setText("Cadastrar Clientes");
        bt_cadastrarcliente.setBorder(null);
        bt_cadastrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarclienteActionPerformed(evt);
            }
        });

        bt_cadastrarpet.setBackground(new java.awt.Color(0, 0, 255));
        bt_cadastrarpet.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        bt_cadastrarpet.setForeground(new java.awt.Color(255, 255, 0));
        bt_cadastrarpet.setText("Cadastrar Pet");
        bt_cadastrarpet.setBorder(null);
        bt_cadastrarpet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarpetActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 255));
        jButton7.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 0));
        jButton7.setText("Sair");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        bt_cadastrarcargo.setBackground(new java.awt.Color(0, 0, 255));
        bt_cadastrarcargo.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        bt_cadastrarcargo.setForeground(new java.awt.Color(255, 255, 0));
        bt_cadastrarcargo.setText("Cadastrar Novo Cargo");
        bt_cadastrarcargo.setBorder(null);
        bt_cadastrarcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrarcargoActionPerformed(evt);
            }
        });

        bt_agendamento.setBackground(new java.awt.Color(0, 0, 255));
        bt_agendamento.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        bt_agendamento.setForeground(new java.awt.Color(255, 255, 0));
        bt_agendamento.setText("Agendamento");
        bt_agendamento.setBorder(null);
        bt_agendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agendamentoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Ravie", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Cadastrar Funcionário");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bt_novoserv, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_verprod, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_cadastrarpet, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_cadastrarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vt_verservico, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_cadastrarprod)))
                            .addComponent(bt_cadastrarcargo)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(bt_agendamento)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cadastrarprod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_verprod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_novoserv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cadastrarpet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cadastrarcliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vt_verservico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cadastrarcargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_agendamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void bt_cadastrarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarprodActionPerformed
        FormCadastrarprod fun = new FormCadastrarprod();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_cadastrarprodActionPerformed

    private void bt_verprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verprodActionPerformed
        FormVerprod fun = new FormVerprod();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_verprodActionPerformed

    private void vt_verservicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vt_verservicoActionPerformed
        FormVerserv fun = new FormVerserv();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vt_verservicoActionPerformed

    private void bt_cadastrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarclienteActionPerformed
        FormCadastrarcliente fun = new FormCadastrarcliente();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_cadastrarclienteActionPerformed

    private void bt_cadastrarpetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarpetActionPerformed
        FormCadastrarpet fun = new FormCadastrarpet();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_cadastrarpetActionPerformed

    private void bt_novoservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoservActionPerformed
        FormCadastrarserv fun = new FormCadastrarserv();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_novoservActionPerformed

    private void bt_cadastrarcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrarcargoActionPerformed
        FormCadastrarcargo fun = new FormCadastrarcargo();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_cadastrarcargoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormCadastrofunc fun = new FormCadastrofunc();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_agendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agendamentoActionPerformed
        FormAgendamento fun = new FormAgendamento();
        fun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_agendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agendamento;
    private javax.swing.JButton bt_cadastrarcargo;
    private javax.swing.JButton bt_cadastrarcliente;
    private javax.swing.JButton bt_cadastrarpet;
    private javax.swing.JButton bt_cadastrarprod;
    private javax.swing.JButton bt_novoserv;
    private javax.swing.JButton bt_verprod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton vt_verservico;
    // End of variables declaration//GEN-END:variables
}
